# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'

User.delete_all
Video.delete_all

u1 = User.create!(username: 'guest', password: 'password')
u2 = User.create!(username: 'jasim', password: 'password')
u3 = User.create!(username: 'noalle', password: 'password')
u4 = User.create!(username: 'nijim', password: 'password')
u5 = User.create!(username: 'jack', password: 'password')

v1 = Video.create!(title: 'Ruby on Rails 101', description: 'Learn everything to get started on building your first app!', user_id: u1.id)
v2 = Video.create!(title: 'Email Hacks', description: 'The different ways that your email can be hacked.', user_id: u2.id)
v3 = Video.create!(title: 'Crypto Hype', description: 'What\'s with all of the hype around cryptos?', user_id: u3.id)
v4 = Video.create!(title: 'World Wide Web', description: 'What is the internet and how does it work?', user_id: u4.id)
v5 = Video.create!(title: 'Jobs in Tech', description: 'A list of all the top tech jobs to start your new career.', user_id: u5.id)
v6 = Video.create!(title: 'Google News', description: 'What\'s new with Google?', user_id: u1.id)
v7 = Video.create!(title: 'How to Properly Disconnect Wires From Your Computer', description: 'A safety guide on how to handle your wires.', user_id: u2.id)
v8 = Video.create!(title: 'CD ROM\'s Are Here to Stay!', description: 'Check out all of the cool new things you can do with CD\'s.', user_id: u3.id)
v9 = Video.create!(title: 'Up Your Google Search Game', description: 'Learn how to make the most of your Google searches.', user_id: u4.id)
v10 = Video.create!(title: 'Map Updates', description: 'We have some cool new updates for your favorite maps app.', user_id: u5.id)
v11 = Video.create!(title: 'Motherboards', description: 'The motherboard is the most important component in the computer. Here\'s why?', user_id: u1.id)
v12 = Video.create!(title: 'Phones and Computers', description: 'We\'re going to show you how to connect that fancy smart phone to an actual computer', user_id: u2.id)
v13 = Video.create!(title: 'Top Tech Podcasts', description: 'Here are the top 15 tech podcasts you should be listening to.', user_id: u3.id)
v14 = Video.create!(title: 'Electronics', description: 'How does electricity become a computer?!?!', user_id: u4.id)
v15 = Video.create!(title: 'Best Tech', description: 'Here\'s the best tech of the year.', user_id: u5.id)
v16 = Video.create!(title: 'Tablet Tests', description: 'We want to know if a tablet is really worth the money.', user_id: u1.id)
v17 = Video.create!(title: 'Cheap Handy Tech', description: 'Here are the best cheap gadgets that you should have.', user_id: u2.id)
v18 = Video.create!(title: 'Fast Hands', description: 'Some of my personal tips on how to improve your typing skills.', user_id: u3.id)

c1 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/1080_HD_computer_keyboard_typing_Ryan.mov')
t1 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/keys-iloveyou-ok-yes-no.jpeg')
c2 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/ICON_VERSION6.mp4')
t2 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/email-address-mail-letter-icon-animation-white-digital-elements-technology-background.jpg')
c3 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/ICON_VERSION7.mp4')
t3 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/keys-commands.jpg')
c4 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/ICON_VERSION8.mp4')
t4 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/recovering-electronics-top-view.jpg')
c5 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/MVI_6852.mp4')
t5 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/back-of-the-computer-close-up.jpg')
c6 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/Video7.mp4')
t6 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/tecnolog-as-en-el-mbito-acad-mico.jpg')
c7 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/back_of_the_computer_.mov')
t7 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/back-of-the-computer.jpg')
c8 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/disc_reader.mov')
t8 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/disc-reader.jpg')
c9 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/google_tech_1080p.mp4')
t9 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/google-tech-1080p.jpg')
c10 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/map_line_connection.mov')
t10 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/mainboard1.jpg')
c11 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/motherboard.mov')
t11 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/motherboard.jpg')
c12 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/phone_and_computer.mov')
t12 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/phone-and-computer.jpg')
c13 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/podcast_key.mp4')
t13 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/ICON-VERSION4.jpg')
c14 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/recovering_electronics.mov')
t14 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/recovering-electronics.jpg')
c15 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/small_laptop_connections.mov')
t15 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/table-and-devices.jpg')
c16 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/tablet_01.mov')
t16 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/ICON-VERSION8_1.jpg')
c17 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/usb_connector.mov')
t17 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/usb-connector.jpg')
c18 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_videos/white_keyboard.mov')
t18 = open('https://boo-tube-seeds.s3.us-east-2.amazonaws.com/tech_stock_images/stock+images/close-up-video-of-hands-typing-on-computer-keyboard.jpg')

v1.video_link.attach(io: c1, filename: '1080_HD_computer_keyboard_typing_Ryan.mov')
v1.thumb_nail.attach(io: t1, filename: 'keys-iloveyou-ok-yes-no.jpeg')
v2.video_link.attach(io: c2, filename: 'ICON_VERSION6.mp4')
v2.thumb_nail.attach(io: t2, filename: 'email-address-mail-letter-icon-animation-white-digital-elements-technology-background.jpg')
v3.video_link.attach(io: c3, filename: 'ICON_VERSION7.mp4')
v3.thumb_nail.attach(io: t3, filename: 'keys-commands.jpg')
v4.video_link.attach(io: c4, filename: 'ICON_VERSION8.mp4')
v4.thumb_nail.attach(io: t4, filename: 'recovering-electronics-top-view.jpg')
v5.video_link.attach(io: c5, filename: 'MVI_6852.mp4')
v5.thumb_nail.attach(io: t5, filename: 'back-of-the-computer-close-up.jpg')
v6.video_link.attach(io: c6, filename: 'Video7.mp4')
v6.thumb_nail.attach(io: t6, filename: 'tecnolog-as-en-el-mbito-acad-mico.jpg')
v7.video_link.attach(io: c7, filename: 'back_of_the_computer_.mov')
v7.thumb_nail.attach(io: t7, filename: 'back-of-the-computer.jpg')
v8.video_link.attach(io: c8, filename: 'disc_reader.mov')
v8.thumb_nail.attach(io: t8, filename: 'disc-reader.jpg')
v9.video_link.attach(io: c9, filename: 'google_tech_1080p.mp4')
v9.thumb_nail.attach(io: t9, filename: 'google-tech-1080p.jpg')
v10.video_link.attach(io: c10, filename: 'map_line_connection.mov')
v10.thumb_nail.attach(io: t10, filename: 'mainboard1.jpg')
v11.video_link.attach(io: c11, filename: 'motherboard.mov')
v11.thumb_nail.attach(io: t11, filename: 'motherboard.jpg')
v12.video_link.attach(io: c12, filename: 'phone_and_computer.mov')
v12.thumb_nail.attach(io: t12, filename: 'phone-and-computer.jpg')
v13.video_link.attach(io: c13, filename: 'podcast_key.mp4')
v13.thumb_nail.attach(io: t13, filename: 'ICON-VERSION4.jpg')
v14.video_link.attach(io: c14, filename: 'recovering_electronics.mov')
v14.thumb_nail.attach(io: t14, filename: 'recovering-electronics.jpg')
v15.video_link.attach(io: c15, filename: 'small_laptop_connections.mov')
v15.thumb_nail.attach(io: t15, filename: 'table-and-devices.jpg')
v16.video_link.attach(io: c16, filename: 'tablet_01.mov')
v16.thumb_nail.attach(io: t16, filename: 'ICON-VERSION8_1.jpg')
v17.video_link.attach(io: c17, filename: 'usb_connector.mov')
v17.thumb_nail.attach(io: t17, filename: 'usb-connector.jpg')
v18.video_link.attach(io: c18, filename: 'white_keyboard.mov')
v18.thumb_nail.attach(io: t18, filename: 'close-up-video-of-hands-typing-on-computer-keyboard.jpg')